name: Build Brise Interpreter

on:
  push:
    branches: [ "main", "t" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install GCC via Mingw
      run: |
        choco install mingw --version=12.2.0 -y
        echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $GITHUB_PATH

    - name: Compile Brise (Static Linking)
      run: |
        # Добавляем флаги статической линковки
        g++ -std=c++17 main.cpp interpreter.cpp -I./libs -o brise.exe -static -static-libgcc -static-libstdc++

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: brise-windows-standalone
        path: brise.exe
